### ISSUE TITLE
AttributeError: _FillValue attribute must be set when variable is created

### ISSUE THREAD

**Issue by nikizadehgfdl** [adcroft/interp_and_fill#1]
I am trying to regrid seawifs to a new hgrid for OM5 and the tool crashes as follows:
```
tools/interp_and_fill/interp_and_fill.py ocean_hgrid.nc ocean_mask.nc seawifs-clim-1997-2010_source.nc  chlor_a  seawifs-clim-1997-2010.nc

Ocean grid shape is 1216 x 1440.
Source data shape = 2160 x 4320.
Super grid shape = 1216 x 2 x 1440 x 2.
Traceback (most recent call last):
  File "tools/interp_and_fill/interp_and_fill.py", line 375, in <module>
    main(args)
  File "tools/interp_and_fill/interp_and_fill.py", line 170, in main
    new_var.setncattr(a, src_data.getncattr(a))
  File "src/netCDF4/_netCDF4.pyx", line 4135, in netCDF4._netCDF4.Variable.setncattr
AttributeError: _FillValue attribute must be set when variable is created (using fill_value keyword to createVariable)
```

This worked fine for 1/8 degree grid two years ago! 
Is this an updated python thing?

**Comment by nikizadehgfdl** [comment]
There was a fix in "master" but I was not using the top of the branch. Closing as user error.
